const { SlashCommandBuilder, AttachmentBuilder } = require("discord.js");

const file = new AttachmentBuilder("../assets/dog.jpg");

module.exports = {
  data: new SlashCommandBuilder()
    .setName("fofa")
    .setDescription("Indireta fofa?"),

  async execute(interaction) {
    await interaction.reply(
      "INDIRETA PRA MIM FOFA??????? KKKKKKKKKKKKKKKKKKKK👌👌👌😂😂😂😂😂😂😂😂👌😂👌KKKK👌👌😂👌😂👌👌😂KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKJKK😂👌😂👌😂👌😂👌😂👌😂😂👌KKKKK JOGA NA MINHA LINHA DO TENPO E MARCA O CANIL DE CACHORAS 🐶🐶👈👊QUE VOSE CHAMA DE BONDE💣💣💥💥 SÓ LEBRO DE VC QUANDO ESCUTO🗣👤 LATIDO🐶🐶 NA RUA SUA CACHORA??🐕🐕, ACHO QUE VOU LIGAR📱📱 PRO IBAMA PRA SABER SE SUA MÃE 👱👱TEM LICENCIA✅📝 PRA TE CRIA, SABE PQ ELA NÃO TE DEIXA SAIR DE CASA?🏠🏠 PORQUE COM ESSA CARA FEIA🐮🐮 QUE VOCÊ TEM ELA TEM MEDO😱😱 DE TE CONFUNDIREM COM UM XIPANZE🙈🙊 E TE LEVAREM🏃➡ PRO ZOOLÓGICO, PROGETO☢☢ DE PUTA,💄👄🖕💅 NEM O INFERNO😈😈 É MAIS QUENTE QUE ESSE FOGO🔥🔥 QUE VOCÊ TEM NO SEU RABO??NEM 5 OCEANOS🌊🌊 ATLÂNTICOS🌊🌊 CONSEGUEM APAGAR🚫🚫🙄😑 ISSO SUA PIRANHA.????🐟🐟😣👊👊 SABE PORK VARIOS KORREM ATRAZ DE VOOC?🏃🏃👈👈 POORK QUANDO A MEREMDA🍓🍈🍊🍉🍌 É DE GRACA A FILA ENCHE👪👫👭 TE ORIENTA IMUDA"
    );
  },
};
